//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineEventRegistrationSystem.Models
{
    using System;
    using System.Collections.Generic;
   

    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Registers = new HashSet<Register>();
        }
        //[RegularExpression(@"^([0-9a-zA-Z]([\+\-_\.][0-9a-zA-Z]+)*)+@(([0-9a-zA-Z][-\w]*[0-9a-zA-Z]*\.)+[a-zA-Z0-9]{2,3})$",
        //ErrorMessage = "Please provide valid email id")]
        //[Required(ErrorMessage = "Please provide Email", AllowEmptyStrings = false)]
        public string Email { get; set; }
        //[Required(ErrorMessage = "Please provide Full Name", AllowEmptyStrings = false)]
        public string FullName { get; set; }
        //[Required(ErrorMessage = "Please provide Address", AllowEmptyStrings = false)]
        public string Address { get; set; }
        //[Required(ErrorMessage = "Please provide Age", AllowEmptyStrings = false)]
        public int Age { get; set; }
        //[Required(ErrorMessage = "Please provide Phone", AllowEmptyStrings = false)]
        public string Phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Register> Registers { get; set; }
    }
}
